version: "3"

services:
  gogs:
    image: gogs/gogs
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-gogs.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.services.${APP_NAME}-gogs.loadBalancer.server.port=3000"
    ports:
      - ${GOGS_SSH_PORT}:22
    volumes:
      - gogs_data:/data
    restart: always

  postgres:
    image: postgres/13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - default
      - web
    restart: always

volumes:
  gogs_data: ~
  postgres_data: ~

networks:
  web:
    external: true
